# version: '3.8'

x-spark-common: &spark-common
  image: wlcamargo/spark-master
  networks:
    - sparkanos

# x-airflow-common: &airflow-common
#   image: apache/airflow:2.9.1
#   environment: &airflow-common-env
#     AIRFLOW__CORE__EXECUTOR: LocalExecutor
#     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
#     AIRFLOW__CORE__FERNET_KEY: ''
#     AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
#     AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
#   volumes:
#     - ./dags:/opt/airflow/dags
#     - ./logs:/opt/airflow/logs
#     - ./plugins:/opt/airflow/plugins
#   user: "${AIRFLOW_UID:-50000}:0"
#   depends_on:
#     - postgres
#   networks:
#     - sparkanos

services: 
  # ----------------
  # MinIO
  # ----------------
  minio: 
    hostname: minio 
    container_name: minio 
    image: 'minio/minio:RELEASE.2024-01-13T07-53-03Z' 
    ports: 
      - '9000:9000' 
      - '9001:9001' 
    volumes: 
      - minio:/data 
    environment: 
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} 
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001" 
    networks: 
      - sparkanos
 
  # ----------------
  # Spark
  # ----------------
  spark-master:
    <<: *spark-common
    hostname: spark-master
    container_name: spark-master
    command: 
      - /bin/sh
      - -c
      - |
        /usr/local/spark/sbin/start-master.sh
        start-notebook.sh --NotebookApp.token=''
    volumes:
      - ./conf/util:/util
      - ./conf/env:/env
      - ./src/Notebooks:/home/user/work
      - ./datasets:/home/user/datasets                # <--- volume compartilhado
      - C:/Users/alcid/Downloads/kaggle.json:/user/.kaggle/kaggle.json:ro
      # - "/c/Users/alcid/Projetos_2025/Ebook/ebook_sparkanos/src/sparkanos/datasets:/datasets"
    environment:
      KAGGLE_CONFIG_DIR: /user/.kaggle
    ports:
      - 8889:8888 # Jupyter
      - 8083:8080 # Spark UI
      - 4040:4040 # Spark UI Jobs
      - 7077:7077 # Default port for communication

#   # ----------------
#   # Airflow infra
#   # ----------------
#   postgres:
#     image: postgres:15
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: airflow
#     volumes:
#       - postgres-db-volume:/var/lib/postgresql/data
#     networks:
#       - sparkanos

#   airflow-webserver:
#     <<: *airflow-common
#     command: webserver
#     ports:
#       - "8080:8080"

#   airflow-scheduler:
#     <<: *airflow-common
#     command: scheduler

#   airflow-init:
#     <<: *airflow-common
#     entrypoint: /bin/bash
#     command:
#       - -c
#       - |
#         airflow db init
#         airflow users create \
#           --username admin \
#           --password admin \
#           --firstname Admin \
#           --lastname User \
#           --role Admin \
#           --email admin@example.com

# ----------------
# Networks & Volumes
# ----------------
networks: 
  sparkanos: 
    driver: bridge 

volumes: 
  minio:
  postgres-db-volume:
